/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

let Punjab2 = React.forwardRef(({ ...props }, ref) => {
    const group = useRef()
    const { nodes, materials } = useGLTF('/Punjab2-transformed.glb')
    
    let [hovering, setHovering] = useState(false);
    let [stuck, setStuck] = useState(false);

    useFrame(({ clock }) => {
        let viewHeight = window.innerHeight;
        // rotate based on scroll
        group.current.rotation.y = -ref.current / 500 - (clock.getElapsedTime() * 0.1);
        // if (hovering) group.current.rotation.x += 10;
    });

    /** keep hover behaviour going for a certain amount of time onClick.
     * @name stickHoverOnClick
     */
    let stickHoverOnClick = () => {
        setHovering(true);
        setStuck(true);
        setTimeout(() => {
            setHovering(false);
            setStuck(false);
        }, 2000);
    }
    let handlePointerLeave = (e) => {
        if (!stuck) setHovering(false);
    }

    return (
        <group 
            ref={group} 
            {...props} 
            dispose={null}
            onClick={ e => stickHoverOnClick() }
            onPointerEnter={ e => setHovering(true) }
            onPointerLeave={ e => handlePointerLeave(e) }
        >
            <mesh 
                geometry={nodes.Map_rivers001.geometry} 
                material={materials['Map_rivers.001']} 
            />
        </group>
    )
})

export default Punjab2;

useGLTF.preload('/Punjab2-transformed.glb')
